# Generated by Django 4.0.3 on 2022-03-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTapp', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='..media/Default/defaultProfilePic.png', upload_to='Profile/'),
        ),
    ]
