# Generated by Django 4.0.3 on 2022-03-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTapp', '0004_alter_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
