# Generated by Django 4.0.3 on 2022-03-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
