# Generated by Django 4.0.3 on 2022-03-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBTapp', '0008_exam_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
