# Generated by Django 4.0.3 on 2022-03-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBTapp', '0009_rename_questions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='cname',
            new_name='ename',
        ),
    ]
